#!/usr/bin/env python3
"""Generate _headers, including a CSP for every language path.

Cloudflare Pages applies EVERY matching rule, and a path matched by two rules
that both set Content-Security-Policy receives TWO CSP headers - browsers then
enforce the intersection, which silently breaks scripts. So `/*` carries every
header EXCEPT the CSP, and the CSP is set exactly once per path.

The reason this file has to be generated: the existing rules are path-scoped,
so `/claim/*` does NOT match `/fr/claim/*`. Shipping the mirrors without these
rules would leave 30 pages with no CSP at all - no script-src, nothing.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from langs import LANGS, prefix

COMMON = """  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin"""

BASE = "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests"

def csp(*extra):
    parts = BASE.split("; ")
    head, tail = parts[0], parts[1:]
    return "; ".join([head] + list(extra) + tail)

# One entry per page family: the paths it occupies under a language prefix,
# and the policy it needs. Comments explain why each directive is present.
FAMILIES = [
    ("home", ["/", "/index.html"],
     csp("script-src 'self'", "img-src data:", "font-src data:"),
     "Home page - runs one same-origin script, /assets/countdown.js. No inline\n"
     "# script, no third-party script, and connect-src stays absent so the page\n"
     "# cannot make a network request of any kind."),

    ("dao", ["/dao/*"],
     csp("script-src 'self'", "img-src data:", "font-src data:"),
     "DAO page - one same-origin script reading balance, voting power and\n"
     "# delegate through the wallet. It can send exactly one transaction:\n"
     "# delegate(address). All RPC goes via the wallet, never the page."),

    ("memes", ["/memes/*"],
     csp("script-src 'self'", "img-src 'self' data: blob:", "media-src blob:", "font-src 'self' data:"),
     "Meme maker - draws to a canvas in the browser. img-src needs data: for\n"
     "# pictures the visitor chooses and blob: for the rendered download.\n"
     "# connect-src stays absent, so a picture physically cannot be sent anywhere."),

    ("leaderboard", ["/leaderboard/*"],
     csp("img-src data:", "font-src data:"),
     "Trading leaderboard - generated nightly, zero JavaScript. The numbers are\n"
     "# computed at build time and baked into the HTML, so no script-src at all."),

    ("claim", ["/claim/*"],
     csp("script-src 'self'", "img-src data:", "font-src data:", "connect-src 'none'"),
     "Claim app - needs JavaScript for wallet access. script-src 'self' permits\n"
     "# only app.js and still blocks every inline and third-party script.\n"
     "# connect-src 'none': wallet calls go through the injected EIP-1193\n"
     "# provider, never through the page."),
]

def build():
    out = ["# Security headers for Cloudflare Pages.",
           "#",
           "# GENERATED by i18n/headers.py - edit that, not this file.",
           "#",
           "# IMPORTANT: Cloudflare applies EVERY matching rule, so a path matched by two",
           "# rules that both set Content-Security-Policy receives two CSP headers, and",
           "# browsers enforce the intersection of them. A blanket `/*` CSP would therefore",
           "# silently override the claim app's script-src and stop app.js from loading.",
           "#",
           "# So: `/*` carries every header EXCEPT the CSP, and the CSP is set exactly once",
           "# per path below - for all " + str(len(LANGS)) + " languages.",
           "",
           "/*", COMMON, ""]

    for name, paths, policy, why in FAMILIES:
        out.append("# " + why)
        for lang in LANGS:
            p = prefix(lang["code"])
            for path in paths:
                full = (p + path) if path != "/" else (p + "/" if p else "/")
                out.append(full)
                out.append(f"  Content-Security-Policy: {policy}")
        out.append("")
    return "\n".join(out)

if __name__ == "__main__":
    root = os.path.dirname(HERE)
    text = build()
    dest = os.path.join(root, "_headers")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, "w").write(text)
    rules = sum(1 for l in text.splitlines() if l.startswith("/"))
    csps = text.count("Content-Security-Policy")
    print(f"  {rules} path rules, {csps} CSP headers -> build/_headers")
